### ISSUE TITLE
mark last move of opponent 

### ISSUE THREAD

**Issue by sharpner** [dazorni/9tac#11]

**Comment by dazorni** [comment]
We could also add a sound if a opponent did a draw

**Comment by sharpner** [comment]
Thats a separate thing, if I didn't pay attention a Soundeffect just reminds me that it is my turn now, but not what has changed on the board. Also I always disable sound on websites :P

**Comment by dazorni** [comment]
okay so maybe this should be another issue with the ability to disable the sound
